Repository where-we-meet/owl, pull requests merged in 2024-04, with the labels that each got.

#10 [feat/room-layout] : 룸페이지 초기 레이아웃
  src/app/room/[id]/page.tsx
  src/app/room/page.tsx
  src/components/room/meeting/Meeting.tsx
  src/components/room/meeting/calender/Calender.tsx
  src/components/room/meeting/place/Place.tsx
  src/components/room/meeting/user/UserList.tsx
Labels: 희철

#14 [dev] 누락된 초기세팅 추가 (prettierrc, resetcss)
  .prettierrc
  src/app/globals.css
  src/app/page.module.css
Labels: 🎨 디자인, 강토, 중요도 낮음

#19 [feat/auth] 소셜로그인 로그아웃
  src/app/auth/callback/route.ts
  src/app/login/page.tsx
  src/app/page.tsx
  src/components/auth/LoginButton.tsx
  src/components/auth/LogoutButton.tsx
  src/middleware.ts
  src/middlewares/authToken.ts
  src/middlewares/chain.ts
  src/middlewares/protectRoute.ts
  src/shared/supabase.ts
  src/utils/supabase/client.ts
  src/utils/supabase/middleware.ts
  src/utils/supabase/server.ts
Labels: 🌟 기능, 의찬

#21 Feature/header
  src/app/layout.tsx
  src/app/page.tsx
  src/components/auth/LogoutButton.tsx
  src/components/layout/Header.module.css
  src/components/layout/Header.tsx
Labels: 🎨 UI / UX, 의찬, 중요도 낮음

#23 [feat] params를 통해 rooms테이블의 데이터를 받아올 수 있는 기능
  src/api/supabase.ts
  src/app/room/[id]/page.tsx
  src/components/room/meeting/user/UserList.tsx
  src/hooks/dummy
  src/hooks/useDataQuery.ts
  src/types/supabase.ts
  src/utils/supabase/server.ts
Labels: 🌟 기능, 강토

#26 design: 지도 마커 이동 효과 추가
  .gitignore
  src/components/room/meeting/place/KakaoMap.module.css
  src/components/room/meeting/place/KakaoMap.tsx
  src/middlewares/authToken.ts
  src/utils/supabase/updateSession.ts
Labels: 🎨 UI / UX, 희철, 중요도 낮음

#25 [Feature/userlist] 유저리스트를 불러오는 기능
  .eslintrc.json
  src/api/supabase.ts
  src/app/room/[id]/page.tsx
  src/components/room/meeting/user/UserList.tsx
  src/components/room/sidebar/Sidebar.tsx
  src/components/room/sidebar/user/UserList.tsx
Labels: 🌟 기능, 강토, 중요도 높음

#30 [feat/map radius] 지도 검색 원 반경 컨트롤러 기능 구현
  src/components/dummy
  src/components/room/meeting/place/KakaoMap.tsx
  src/components/room/meeting/place/RangeController.module.css
  src/components/room/meeting/place/RangeController.tsx
Labels: 🎨 디자인, 🌟 기능, 의찬

#38 [feat/room-place_search] 지도 검색, 검색 결과 선택시 중심 이동 기능 구현
  package.json
  src/api/place/placeData.ts
  src/app/room/[id]/page.tsx
  src/components/room/meeting/place/KakaoMap.tsx
  src/components/room/meeting/place/Place.tsx
  src/components/room/meeting/place/search/SearchBar.module.css
  src/components/room/meeting/place/search/SearchBar.tsx
  src/components/room/meeting/place/search/SearchResultList.module.css
  src/components/room/meeting/place/search/SearchResultList.tsx
  src/hooks/useGetPlace.ts
  src/hooks/useGetRoadAddress.ts
  src/store/dummy
  src/store/store.ts
  src/types/place.types.ts
  src/utils/place/changeToViewPoint.ts
  src/utils/place/dragCenter.ts
  yarn.lock
Labels: 🌟 기능, 희철

#35 [feat/meeting] 모임 방 정보 조회 및 이동 구현
  src/app/my-owl/page.tsx
  src/components/my-owl/meeting/Meeting.module.css
  src/components/my-owl/meeting/Meeting.tsx
Labels: 🌟 기능, 🎨 UI / UX, 참

#42 [fix/build] Invariant: cookies() expects to have requestAsyncStorage, none available 빌드 에러 수정
  src/app/page.tsx
  src/components/auth/LogoutButton.tsx
  src/components/my-owl/profile/Profile.tsx
Labels: 🐛 버그, 의찬, 중요도 낮음

#57 fix: 로그인 페이지 헤더 숨기기
  src/app/login/page.module.css
  src/components/layout/Header.tsx
Labels: 의찬, 중요도 낮음

#59 [feat/show schedule] 다른 유저가 선택한 일정 위에 중복 선택 가능
  src/components/room/meeting/Meeting.tsx
  src/components/room/meeting/calender/Calender.tsx
Labels: ✨기능, 소향, ⬆️ 중요도 높음

#87 [Refactor/myowl] my-owl 페이지의 UserInfo.tsx 및 Modal.tsx 코드 Refactoring
  src/components/my-owl/profile/editable/UserInfo.tsx
  src/components/my-owl/profile/editable/modal/Modal.tsx
Labels: 참, ⬇️ 중요도 낮음, 🧑‍💻리팩토링

#100 [feat/setting-layout] room 레이아웃 생성
  src/app/room/[id]/(setting)/layout.tsx
  src/app/room/[id]/(setting)/pick-calendar/page.tsx
  src/app/room/[id]/(setting)/pick-place/page.tsx
Labels: ✨기능, 소향

#139 [refactor/calendar] selectedDate를 zustand를 이용하여 전역상태로 관리
  src/components/room/meeting/calender/Calender.tsx
  src/store/calendarStore.ts
Labels: 소향, 🧑‍💻리팩토링

#144 [fix gc] user 데이터 undefined로 GC되는 이슈 임시 해결
  src/app/layout.tsx
  src/app/providers.tsx
Labels: 🐛 버그, 참

#145 refactor: 리액트쿼리 적용, 필요없는 로직 제거
  src/hooks/useGetRoomData.ts
Labels: 의찬, 🧑‍💻리팩토링

#155 [feat] supabase 로그인 리다이렉션 링크, 배포 링크 환경변수로 설정
  src/components/auth/LoginButton.tsx
Labels: ✨기능, 의찬

#167 feat: 룸 설정 확정 기능 생성
  src/api/room.ts
  src/api/supabaseCSR/supabase.ts
  src/app/room/[id]/(setting)/confirm/page.tsx
  src/components/room/meeting/calender/Calender.tsx
  src/hooks/useMutateUserData.ts
  src/store/calendarStore.ts
  src/types/roomUser.ts
  src/utils/sortDate.ts
Labels: ✨기능, 희철

#171 [fix/session-storage] 저장시 session storage clear
  src/app/room/[id]/(setting)/confirm/page.tsx
Labels: 희철, 🧑‍💻리팩토링

#181 style: 웹페이지 전체 폰트 적용
  src/app/globals.css
Labels: 🎨 디자인, 소향

#180 [style] 유저 소셜 로그인 정보 아이콘 ui 수정
  src/components/header/UserProfileRead.module.css
Labels: 🎨 UI / UX, 참

#184 [style] start 페이지 스타일
  src/components/room/StartMeeting.module.css
  src/components/room/StartMeeting.tsx
Labels: 참

#191 [feat] 유저캘린더에서 데이터를 받아오는 형식을 data, mydata, anotherUserData 로 분류
  src/api/supabaseCSR/supabase.ts
  src/app/room/[id]/(setting)/pick-calendar/page.tsx
  src/components/room/meeting/calender/Calender.tsx
  src/hooks/useGetCalendar.ts
  src/hooks/useGetSchedule.ts
Labels: ✨기능, 강토, ⬆️ 중요도 높음, 🧑‍💻리팩토링

#200 [fix/default-range] range 단위 변경으로 인해 store에서 초기값 수정 300 -> 200
  src/store/placeStore.ts
Labels: 희철, ⬇️ 중요도 낮음, 🧑‍💻리팩토링

#204 [fix/calendar]: 일정 수정 시, 세션 스토리지에 저장 후 확정 페이지로 넘어감
  src/app/room/[id]/(setting)/pick-calendar/page.tsx
  src/hooks/useGetSchedule.ts
Labels: 🐛 버그, 소향, ⬆️ 중요도 높음

#205 [fix/profile modal] 프로필 모달 창 뒤로가기 이슈 해결
  src/components/header/ProfileModal.module.css
  src/components/header/ProfileModal.tsx
  src/components/header/UserProfileButton.module.css
  src/components/header/UserProfileButton.tsx
  src/components/header/UserProfileRead.tsx
  src/components/header/UserProfileUpdate.tsx
Labels: 🐛 버그, ✨기능, 참, ⬆️ 중요도 높음

#208 [fix/confirm] setting/confirm의 upsertRoomUser, upsertSchedule 수정
  src/app/room/[id]/(setting)/confirm/page.tsx
Labels: 희철, 🧑‍💻리팩토링

#207 [fix/in app browser] 카카오톡 인앱브라우저에서 구글 로그인 시도 시, 403 에러
  src/app/room/[id]/layout.tsx
Labels: 🐛 버그, 소향

#212 [fix/error] iOS 및 기타 브라우저 최신 문법 적용 이슈 해결
  src/utils/groupBy.ts
  src/utils/mostSchedule.ts
Labels: 🐛 버그, 참

#220 [fix/calendar]: 일정 페이지 입장 시, 범위를 기준으로 달력 렌더링
  src/components/room/meeting/calender/Calender.tsx
Labels: 🐛 버그, 소향

#245 [style/locationSwitch]: 위치 지정 토글 style 변경
  src/components/room/place/LocationSwitch.module.css
  src/components/room/place/LocationSwitch.tsx
Labels: 희철

#253 [fix/useQueryPlace] queryKey이름, gcTime 5분으로 변경
  src/hooks/useQueryPlace.ts
Labels: 희철, ⬇️ 중요도 낮음

#258 [feat/search bar] "X" 아이콘 추가하여 검색어 초기화
  src/components/room/place/search/SearchBar.tsx
Labels: ✨기능, 소향

#262 [fix/start-location-box] 출발 위치 고정일 때 지도 이동 시 출발 위치 내용도 고정으로 수정
  src/components/room/place/StartLocationBox.tsx
Labels: 🐛 버그, 희철, 🧑‍💻리팩토링

#278 [fix/auth-delete] google revoke request config params 수정
  src/app/auth/delete/route.ts
Labels: 🐛 버그, 희철

#286 [style] 모임페이지 스타일 수정, 맵 리렌더링 딜레이
  src/app/globals.css
  src/app/providers.tsx
  src/app/room/[id]/page.module.css
  src/components/room/chatRoom/ChatRoom.module.css
  src/components/room/place/SettingMap.module.css
  src/components/room/place/SettingMap.tsx
  src/components/room/place/StartLocationBox.module.css
  src/components/room/sidebar/Sidebar.module.css
  src/components/room/sidebar/user/UserCard.module.css
Labels: 🎨 디자인, 🎨 UI / UX, 의찬

#287 [style/user-marker] 유저 마커 스타일 커스텀
  src/components/room/place/UserMarker.module.css
  src/components/room/place/UserMarker.tsx
Labels: 🎨 디자인, 희철

#308 [style/categoryInfo] 카테고리 정보 zIndex 수정
  src/components/room/place/search/CategoryMarker.tsx
Labels: 🎨 디자인, 🎨 UI / UX, 희철

#309 [fix/chatroom] 모바일 채팅창 터치 대응
  src/components/loading.tsx
  src/components/room/chatRoom/InputBox.module.css
  src/components/room/chatRoom/InputBox.tsx
Labels: 🐛 버그, 강토, ⬇️ 중요도 낮음
